import { Config } from '../types';

export function generateHttpHeaders(config: Config): string {
  const sections: string[] = [];

  sections.push('# ══════════════════════════════════════════');
  sections.push('# Recommended HTTP Headers for AI Agents');
  sections.push(`# Generated by ax-init for ${config.url}`);
  sections.push('# ══════════════════════════════════════════');

  const policy = config.crawlerPolicy === 'allow' ? 'index, follow' : 'noindex, nofollow';

  // Nginx
  sections.push('');
  sections.push('# ── Nginx ──');
  sections.push('');
  sections.push('# Add to your server {} or location / {} block:');
  sections.push(`add_header X-Robots-Tag "${policy}, noai" always;`);
  sections.push(`add_header Link '<${config.url}/llms.txt>; rel="alternate"; type="text/plain"; title="LLM-readable"' always;`);
  sections.push(`add_header Link '<${config.url}/.well-known/agent.json>; rel="agent"; type="application/json"' always;`);

  // Apache
  sections.push('');
  sections.push('# ── Apache (.htaccess) ──');
  sections.push('');
  sections.push('Header set X-Robots-Tag "' + policy + ', noai"');
  sections.push(`Header add Link "<${config.url}/llms.txt>; rel=\\"alternate\\"; type=\\"text/plain\\"; title=\\"LLM-readable\\""'`);
  sections.push(`Header add Link "<${config.url}/.well-known/agent.json>; rel=\\"agent\\"; type=\\"application/json\\""'`);

  // Vercel (vercel.json)
  sections.push('');
  sections.push('# ── Vercel (vercel.json) ──');
  sections.push('');
  sections.push(JSON.stringify({
    headers: [
      {
        source: '/(.*)',
        headers: [
          { key: 'X-Robots-Tag', value: `${policy}, noai` },
          { key: 'Link', value: `<${config.url}/llms.txt>; rel="alternate"; type="text/plain"; title="LLM-readable"` },
        ],
      },
    ],
  }, null, 2));

  // Netlify (_headers)
  sections.push('');
  sections.push('# ── Netlify (_headers) ──');
  sections.push('');
  sections.push('/*');
  sections.push(`  X-Robots-Tag: ${policy}, noai`);
  sections.push(`  Link: <${config.url}/llms.txt>; rel="alternate"; type="text/plain"; title="LLM-readable"`);

  sections.push('');

  return sections.join('\n');
}
