import { Config } from '../types';

const AI_CRAWLERS = [
  // Core AI crawlers
  'GPTBot',
  'ChatGPT-User',
  'ClaudeBot',
  'Claude-Web',
  'Google-Extended',
  'Amazonbot',
  // Additional AI crawlers
  'Bytespider',
  'CCBot',
  'PerplexityBot',
  'YouBot',
  'Cohere-ai',
  'anthropic-ai',
  'Meta-ExternalAgent',
  'FacebookBot',
  'Applebot-Extended',
  'OAI-SearchBot',
  'AI2Bot',
  'Diffbot',
  'Omgilibot',
  'Timpibot',
  'img2dataset',
  'PetalBot',
];

export function generateRobotsTxt(config: Config): string {
  const lines: string[] = [];

  lines.push('# ══════════════════════════════════════════');
  lines.push('# AI Crawler Rules');
  lines.push(`# Generated by ax-init for ${config.url}`);
  lines.push('# ══════════════════════════════════════════');
  lines.push('');

  if (config.crawlerPolicy === 'allow') {
    lines.push('# Policy: Allow AI crawlers');
    lines.push('');
    for (const crawler of AI_CRAWLERS) {
      lines.push(`User-agent: ${crawler}`);
      lines.push('Allow: /');
      lines.push('');
    }
  } else {
    lines.push('# Policy: Block AI crawlers');
    lines.push('');
    for (const crawler of AI_CRAWLERS) {
      lines.push(`User-agent: ${crawler}`);
      lines.push('Disallow: /');
      lines.push('');
    }
  }

  lines.push('# Sitemap');
  lines.push(`Sitemap: ${config.url}/sitemap.xml`);
  lines.push('');

  return lines.join('\n');
}
