import { Config } from '../types';

export function generateSecurityTxt(config: Config): string {
  // Expires 1 year from generation
  const expires = new Date();
  expires.setFullYear(expires.getFullYear() + 1);

  const lines: string[] = [];

  lines.push(`# Security policy for ${config.name}`);
  lines.push(`# Generated by ax-init`);
  lines.push('');
  lines.push(`Contact: mailto:${config.contactEmail}`);
  lines.push(`Expires: ${expires.toISOString()}`);
  lines.push(`Preferred-Languages: ${config.languages.join(', ')}`);
  lines.push(`Canonical: ${config.url}/.well-known/security.txt`);
  lines.push('');

  return lines.join('\n');
}
